-- If the Team page only lists the signed-in user, RLS on `profiles` may be blocking reads of other rows,
-- or other auth users may be missing `profiles` rows.
--
-- Use the ready-to-run script (backfill + policy + trigger):
--   profiles_team_complete.sql
